apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpujupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpujupyter
  template:
    metadata:
      labels:
        app: gpujupyter
    spec:
      containers:
      - name: gpujupyter
        image: tensorflow/tensorflow:latest-gpu-py3-jupyter
        ports:
        - containerPort: 8888
        volumeMounts:
        - mountPath: /tf
          name: j-books
      volumes:
      - name: j-books
        persistentVolumeClaim:
          claimName: gggpvc
      nodeSelector:
        accelerator: nvidia-gt710
---
apiVersion: v1
kind: Service
metadata:
  name: gpujupyter
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    name: tcp
  selector:
    app: gpujupyter
