apiVersion: v1 #version of the API to use
kind: Pod #What kind of object we're deploying
metadata: #information about our object we're deploying
  name: jupyter-pod
spec: #specifications for our object
  containers:
  - name: jupyter-container #the name of the container within the pod
    image: jupyter/tensorflow-notebook #which container image should be pulled
    ports:
    - containerPort: 8888 #the port of the container within the pod
